- Dockerfile
This PR addresses the following ecosystem-cert-preflight-check issues:
- add LICENCE: addresses `"Checking if terms and conditions applicable to the software including open source licensing information are present. The license must be at /licenses"`
- declare a non-root USER: addresses `"Checking if container runs as the root user because a container that does not specify a non-root user will fail the automatic certification, and will be subject to a manual review before the container can be approved for publication"`
> Add LICENCE and USER to Dockerfile

- api/v1alpha1/siteconfig_types.go
- bundle/manifests/metaclusterinstall.openshift.io_siteconfigs.yaml
- bundle/manifests/siteconfig.clusterserviceversion.yaml
- config/crd/bases/metaclusterinstall.openshift.io_siteconfigs.yaml
- config/rbac/role.yaml
- go.mod
- internal/controller/siteconfig_controller.go
- internal/controller/siteconfig_controller_test.go
This commit refactors the SiteConfig finalizer to handle ordered deletion of rendered manifests by descending order of the sync-wave.
> CNF-13328: Handle ordered deletion of rendered manifests

- internal/controller/clusterinstance/helper.go
- internal/controller/clusterinstance/helper_test.go
- internal/controller/clusterinstance/template_engine_test.go
- internal/controller/clusterinstance/test_utils.go
- internal/controller/clusterinstance_controller_test.go
- internal/templates/assisted-installer/template.go
- internal/templates/image-based-install/template.go
This PR contains the change to rename the `ClusterData` object `Site` field to `Spec`.
> CNF-13563: Rename ClusterData Site field to Spec

- api/v1alpha1/clusterinstance_types.go
- bundle/manifests/siteconfig.open-cluster-management.io_clusterinstances.yaml
- config/crd/bases/siteconfig.open-cluster-management.io_clusterinstances.yaml
This PR cleans-up the `ClusterInstance` CRD by explicitly tagging fields as required and optional. Required fields that have the `omitempty` json tag are also fixed.
> CNF-13547: Explicitly flag required and optional fields in the ClusterInstance CRD

- internal/templates/assisted-installer/template.go
- internal/templates/image-based-install/template.go
This PR contains changes to the default templates in the SiteConfig operator. Specifically, the templates which have fields that are json strings are updated with quotes.
> Add quotes to json string fields in default AI and IBI templates

- internal/templates/assisted-installer/template.go
This PR contains the change to replace the deprecated `AgentClusterInstall` template field `manifestsConfigMapRef` with `manifestsConfigMapRefs`.
The sample ACI CR below confirms the change.
```yaml
apiVersion: extensions.hive.openshift.io/v1beta1
kind: AgentClusterInstall
metadata:
annotations:
agent-install.openshift.io/install-config-overrides: '{"networking":{"networkType":"OVNKubernetes"},"capabilities":{"baselineCapabilitySet": "None", "additionalEnabledCapabilities": [ "marketplace", "NodeTuning" ] }}'
siteconfig.open-cluster-management.io/sync-wave: "1"
creationTimestamp: "2024-07-11T14:23:21Z"
finalizers:
- agentclusterinstall.agent-install.openshift.io/ai-deprovision
generation: 4
name: cnfdg6
namespace: cnfdg6
ownerReferences:
- apiVersion: …
```
> Update AgentClusterInstall template to use manifestsConfigMapRefs

- api/v1alpha1/clusterinstance_types.go
- bundle/manifests/siteconfig.open-cluster-management.io_clusterinstances.yaml
- config/crd/bases/siteconfig.open-cluster-management.io_clusterinstances.yaml
- internal/controller/clusterdeployment_reconciler.go
- internal/controller/clusterdeployment_reconciler_test.go
- internal/controller/conditions/conditions.go
This PR updates the `ClusterInstance` `Provisioned` condition status to reflect the following:
- `Failed` provisioning when the `ClusterDeployment.Status.Conditions` are as follows: `ClusterInstallStopped.Status==True` and `ClusterInstallFailed.Status==True`,
- `Unknown` status when `ClusterDeployment.Spec.Installed==True` but the `ClusterDeployment.Status.Conditions` have not been updated,
- Successful provisioning (`Completed`) is now only set when the `ClusterDeployment.Status.Conditions` are as follows: `ClusterInstallCompleted.Status==True` and `ClusterInstallStopped.Status==True`.
The `ClusterInstance` columns are also updated to reflect the provisioning status:
```sh
$ oc get clusterinstance -A
NAMESPACE   NAME     PROVISIONSTATUS   PROVISIONDETAILS       AGE
cnfdg6      cnfdg6 …
```
> CNF-13781: Refine ClusterInstance Provisioned condition status

- .tekton/siteconfig-main-pull-request.yaml
- .tekton/siteconfig-main-push.yaml
This commit migrates the konflux-ci buildah from 0.1 to 0.2. The migration steps are outlined here: https://github.com/konflux-ci/build-definitions/blob/main/task/buildah/0.2/MIGRATION.md.
> CNF-14021: Migrate buildah from 0.1 to 0.2

- api/v1alpha1/clusterinstance_types.go
- bundle/manifests/siteconfig.open-cluster-management.io_clusterinstances.yaml
- config/crd/bases/siteconfig.open-cluster-management.io_clusterinstances.yaml
- internal/controller/clusterdeployment_reconciler.go
- internal/controller/clusterdeployment_reconciler_test.go
- internal/controller/clusterinstance_controller.go
- internal/controller/clusterinstance_controller_test.go
- internal/controller/conditions/conditions.go
- internal/controller/conditions/conditions_test.go
This PR introduces an API change to `ClusterInstance.Status`. Specifically, the `ObservedGeneration` field is added. This field is updated to match the `ClusterInstance.ObectMeta.Generation` field each time an update/patch request is made to the `ClusterInstance`.
This change allows for avoiding unnecessary reconciles of the `ClusterInstance` CR which can be triggered when there is no change in the `ClusterInstance` spec fields and the controller pod is restarted (either due to an error or an upgrade).
The PR also introduces cosmetic changes by renaming some of the update/patch/find functions in `conditions.go`.
The PR was manually tested by provisioning a cluster with the default assisted-installer templates. After provisioning was completed, the controller-manager pod was restarted. …
> CNF-13987: Add ObservedGeneration to ClusterInstance.Status

- internal/controller/clusterinstance/helper.go
- internal/controller/clusterinstance/helper_test.go
- internal/controller/clusterinstance/template_engine.go
- internal/controller/clusterinstance/template_engine_test.go
This PR adds the following `owned-by` label to all rendered manifests (both cluster-scoped and namespace-scoped resources):
```yaml
siteconfig.open-cluster-management.io/owned-by: <clusterinstance-namespace>_<clusterinstance-name>
```
This label is required since the SiteConfig operator is namespace-scoped and cannot set the `OwnerRef` on cluster-scoped resources such as Namespaces and ManagedClusters.
This label will be used to handle pruning and deletion of rendered manifests.
Below are examples of rendered manifests with the new label applied by the SiteConfig operator:
```yaml
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
...
labels:
cluster.open-cluster-management.io/clusterset: default
common: "true"
group-du-48core: ""
hare: krsna
name: cnfdg6 …
```
> CNF-14191: Add owned-by label to rendered manifests

- api/v1alpha1/clusterinstance_types.go
- api/v1alpha1/clusterinstance_utils.go
- api/v1alpha1/clusterinstance_utils_test.go
- api/v1alpha1/zz_generated.deepcopy.go
- bundle/manifests/siteconfig.open-cluster-management.io_clusterinstances.yaml
- config/crd/bases/siteconfig.open-cluster-management.io_clusterinstances.yaml
- internal/controller/clusterinstance/template_engine.go
- internal/controller/clusterinstance/template_engine_test.go
This PR enables the user to configure additional labels to both cluster and node manifests through new `ExtraLabels` fields in the `ClusterInstance` API. 
Below are examples of rendered manifests with extra labels applied by the SiteConfig operator for the given `ClusterInstance`:
```yaml
apiVersion: siteconfig.open-cluster-management.io/v1alpha1
kind: ClusterInstance
metadata:
name: "cnfdg6"
namespace: "cnfdg6"
spec:
...
clusterName: "cnfdg6"
extraLabels:
ManagedCluster:
common: "true"
group-du-48core: ""
sites : "cnfdg6"
vendor: "auto-detect"
nodes:
- hostName: "cnfdg6.ptp.eng.rdu2.dc.redhat.com"
role: "master"
extraLabels:
BareMetalHost:
"testExtraLabel": "success"
...
```
```sh
$ oc get managedclusters cnfdg6 -ojsonpath='{.metadata.labels}' | jq
{ …
```
> CNF-13357: Enable extra labels to be configured through ClusterInstance

- api/v1alpha1/clusterinstance_types.go
- api/v1alpha1/zz_generated.deepcopy.go
- bundle/manifests/siteconfig.clusterserviceversion.yaml
- bundle/manifests/siteconfig.open-cluster-management.io_clusterinstances.yaml
- config/crd/bases/siteconfig.open-cluster-management.io_clusterinstances.yaml
- config/samples/siteconfig_v1alpha1_clusterinstance.yaml
- internal/controller/clusterinstance/template_engine_test.go
- internal/templates/assisted-installer/template.go
- internal/templates/image-based-install/template.go
This PR removes the `ClusterLabels` field from the `ClusterInstance` API. This field is no longer required since cluster labels should be specified through the recently introduced `ExtraLabels` field (https://github.com/stolostron/siteconfig/pull/75) with the key `ManagedCluster` as shown in the example below.
```yaml
apiVersion: siteconfig.open-cluster-management.io/v1alpha1
kind: ClusterInstance
metadata:
name: "cnfdg6"
namespace: "cnfdg6"
spec:
...
clusterName: "cnfdg6"
extraLabels:
ManagedCluster:
common: "true"
group-du-48core: ""
sites : "cnfdg6"
vendor: "auto-detect"
```
> CNF-14215: Remove ClusterLabels from ClusterInstance API

- internal/controller/clusterdeployment_reconciler.go
- internal/controller/clusterdeployment_reconciler_test.go
- internal/controller/clusterinstance/helper.go
- internal/controller/clusterinstance/template_engine.go
- internal/controller/clusterinstance/template_engine_test.go
- internal/controller/clusterinstance_controller.go
- internal/controller/clusterinstance_controller_test.go
This PR contains the changes to enable a user to retain resources rendered by the SiteConfig operator upon deletion of the `ClusterInstance` object responsible for its creation. This is accomplished by filtering on rendered resources that contain a matching `ownedBy` label corresponding to the `ClusterInstance` object.
This PR also removes the setting of the Kubernetes `OwnerReference` as it only applies to Namespace-scoped resources whereas the previously added `ownedBy` label supports ownership of both Cluster-scoped and Namespace-scoped resources.
> CNF-14211: Delete manifests owned by the ClusterInstance

- api/v1alpha1/clusterinstance_types.go
- bundle/manifests/siteconfig.open-cluster-management.io_clusterinstances.yaml
- config/crd/bases/siteconfig.open-cluster-management.io_clusterinstances.yaml
- internal/templates/assisted-installer/template.go
This PR exposes the `platformType` field in the `ClusterInstance` API. This field is consumed by the `AgentClusterInstall` manifest. 
The corresponding ACI template is updated to include the `platformType` field if specified in the `ClusterInstance` CR.
> CNF-14561: Expose platform field for AgentClusterInstall in the ClusterInstance API

- internal/controller/clusterinstance/template_engine_test.go
- internal/templates/assisted-installer/template.go
- internal/templates/image-based-install/template.go
This PR updates the default `BareMetalHost` install templates for Assisted Installer and Image Based Installer to handle the `NodeSpec.NodeLabels` in the same way as the old SiteConfig implementation (https://github.com/openshift-kni/cnf-features-deploy/pull/1485/commits/77cc48c625b786046be6554364cf3eb5b08e729e)
Specifically, the `NodeLabels` are appended to the `BareMetalHost` annotations with the `bmac.agent-install.openshift.io` prefix.
> ACM-14519: Apply nodeLabel to default BareMetalHost templates

- api/v1alpha1/clusterinstance_types.go
- internal/controller/clusterinstance/helper.go
- internal/controller/clusterinstance/helper_test.go
- internal/controller/clusterinstance/rendered_object.go
- internal/controller/clusterinstance/rendered_object_test.go
- internal/controller/clusterinstance/template_engine.go
- internal/controller/clusterinstance/template_engine_test.go
- internal/controller/clusterinstance/test_utils.go
- internal/controller/clusterinstance_controller.go
- internal/controller/clusterinstance_controller_test.go
This PR introduces the ability to prune manifests created and owned by the `ClusterInstance`. To implement this, new data structures: `RenderedObject` and `RenderedObjectCollection` have been added. The `RenderedObject` consists of an `object` (as `unstructured.Unstructured`) and an `action` field that defines whether the manifest should be rendered, suppressed, or pruned.
These new structures are used to refactor key logic in both the `template_engine` and `clusterinstance_controller` components.
- Added the `RenderedObject` and `RenderedObjectCollection` types to handle template rendering / suppression / pruning functionality.
- Refactored the `template_engine` and `clusterinstance_controller` files to use the new data structures.
- Updated existing unit tests to cover these changes.
- …
> CNF-14190: Add support for pruning manifests owned by ClusterInstance

- api/v1alpha1/clusterinstance_conditions.go
- internal/controller/clusterdeployment_reconciler.go
- internal/controller/clusterdeployment_reconciler_test.go
- internal/controller/clusterinstance_controller.go
- internal/controller/clusterinstance_controller_test.go
- internal/controller/conditions/conditions.go
- internal/controller/conditions/conditions_test.go
This PR exposes the `ClusterInstance` `ConditionType` and `ConditionReason` so that it may be consumed by other operators.
> ACM-14493: Expose the ClusterInstance ConditionType and ConditionReason

- internal/templates/image-based-install/template.go
https://issues.redhat.com/browse/ACM-14649
Merge after https://github.com/openshift/image-based-install-operator/pull/125
> ACM-14649: Pluralize the extra manifests field name in the IBI templates

- internal/templates/image-based-install/template.go
This PR sets the `externallyProvisioned: true` BMH spec field for the IBI template.
Resolves: https://issues.redhat.com/browse/ACM-14672
> ACM-14672: Set externallyProvisioned in IBI BMH template

- cmd/main.go
- cmd/main_test.go
- go.mod
- internal/controller/clusterdeployment_reconciler.go
- internal/controller/clusterdeployment_reconciler_test.go
- internal/controller/clusterinstance/template_engine.go
- internal/controller/clusterinstance/template_engine_test.go
- internal/controller/clusterinstance_controller.go
- internal/controller/clusterinstance_controller_test.go
This PR replaces the current logger `go-logr` with the zap logger with added contextual information about the `ClusterInstance` or `ClusterDeployment` objects as well as useful function names (where relevant to aid debugging). Furthermore, some of the log messages have been converted from `Info` to `Debug`.
Resolves: [CNF-14769](https://issues.redhat.com/browse/CNF-14769)
> CNF-14769: Refactor logging to use zap logger directly with contextual information

- internal/templates/image-based-install/template.go
This PR introduces a `preprovisioningNetworkDataName` guard in the IBI-BMH template to support deploying a DHCP spoke cluster.
Resolves [ACM-14164](https://issues.redhat.com/browse/ACM-14164)
> ACM-14164: Add preprovisioningNetworkDataName guard to IBI BMH template

- internal/templates/assisted-installer/template.go
- internal/templates/image-based-install/template.go
This PR removes the `cloud` and `vendor` labels from the KlusterletAddonConfig template and adds them to the ManagedCluster template for both Assisted Installer and Image Based Installer to support enabling ACM observability without user intervention (reference: https://docs.redhat.com/en/documentation/red_hat_advanced_cluster_management_for_kubernetes/2.11/html/clusters/cluster_mce_overview#preparing-cluster-import).
Resolves: [ACM-14738](https://issues.redhat.com/browse/ACM-14738)
> ACM-14738: Add observability labels to ManagedCluster template for AI and IBI

- cmd/main.go
- cmd/main_test.go
- internal/controller/clusterinstance_controller.go
- internal/controller/clusterinstance_controller_test.go
- internal/controller/suite_test.go
- internal/templates/assisted-installer/template.go
- internal/templates/image-based-installer/template.go
This PR applies the ACM disaster recovery backup label (`cluster.open-cluster-management.io/backup: ""`) to custom install template ConfigMaps. The default Assisted Installer (AI) and Image Based Installer (IBI) templates are not included in the content to be backed up as these are automatically created when the SiteConfig Operattor manager pod starts.
Note that the following content, required by the SiteConfig Operator and ClusterInstance controller, should already be backed up by the underlying installers (i.e. AI or IBI) and are thus excluded from the SiteConfig Operator:
- pull secret
- BMC secrets
- extra-manifests ConfigMaps
Furthermore,  the ClusterInstance CRs (`clusterinstances.siteconfig.open-cluster-management.io`) should automatically be backed up by ACM as per …
> ACM-13268: Apply ACM disaster recovery backup label to custom install templates

- internal/controller/clusterinstance/template_engine_test.go
- internal/controller/clusterinstance/test_utils.go
- internal/templates/image-based-installer/template.go
This PR updates the ImageClusterInstall IBI template to make use of the first `machineNetwork` value defined in the ClusterInstance.spec to align with the Image Based Install Operator's API specification of MachineNetwork as a [string](https://github.com/openshift/image-based-install-operator/blob/main/api/v1alpha1/imageclusterinstall_types.go#L98) value.
Resolves: [ACM-14955](https://issues.redhat.com/browse/ACM-14955)
> ACM-14955: Extract machineNetwork for IBI template

- internal/templates/image-based-installer/template.go
This PR updates the default IBI ClusterDeployment template by assigning the appropriate value to the platform field.
Resolves: [ACM-15169](https://issues.redhat.com/browse/ACM-15169)
> ACM-15169: Update ClusterDeployment template for IBI

- internal/templates/image-based-installer/template.go
This PR cleans-up unused and not relevant annotations pertaining to the default IBI/BMH template.
Resolves: [ACM-15118](https://issues.redhat.com/browse/ACM-15118)
> ACM-15118: Cleanup BMH template for IBI

- .tekton/siteconfig-main-pull-request.yaml
- .tekton/siteconfig-main-push.yaml
This PR removes the deprecated `sbom-json-check` task from the konflux pipeline. Reference: https://github.com/konflux-ci/build-definitions/commit/76a2742f82f377441da39636b3b7ed10a8e62d2f.
> Remove deprecated sbom-json-check task from konflux pipelines

- api/v1alpha1/clusterinstance_conditions.go
This PR introduces new reinstall ConditionTypes and ConditionReasons for the ClusterInstance API.
**Resolves:** [CNF-15743](https://issues.redhat.com/browse/CNF-15743)
> CNF-15743: Add new reinstall status ConditionTypes and ConditionReasons

- cmd/main.go
- cmd/main_test.go
- docs/configure_siteconfig.md
- internal/controller/clusterinstance/suite_test.go
- internal/controller/clusterinstance_controller.go
- internal/controller/clusterinstance_controller_test.go
- internal/controller/configuration/configuration.go
- internal/controller/configuration/configuration_store.go
- internal/controller/configuration/configuration_store_test.go
- internal/controller/configuration/configuration_test.go
- internal/controller/configuration/suite_test.go
- internal/controller/configuration_monitor.go
- internal/controller/configuration_monitor_test.go
This PR introduces functionality to manage the SiteConfig Operator's configuration via a ConfigMap.
A new controller, `ConfigurationMonitor`, has been implemented to monitor and maintain the configuration. Key features include:
- Automatic creation of the ConfigMap with default values during manager pod initialization if it doesn't exist.
- Re-creation of the ConfigMap with default values if it is deleted.
The following configuration fields are supported:
- `AllowReinstalls`: Enables or disables the reinstall functionality.
- `MaxConcurrentReconciles`: Sets the maximum number of `ClusterInstances` that can be processed concurrently.
Unit tests have been added to validate the behavior of the new components.
**Resolves**: [CNF-15718](https://issues.redhat.com/browse/CNF-15718)
> CNF-15718: Add Configuration Support for the SiteConfig Operator

- api/v1alpha1/clusterinstance_conditions.go
- api/v1alpha1/clusterinstance_types.go
- api/v1alpha1/clusterinstance_utils.go
- cmd/main.go
- go.mod
- internal/controller/clusterinstance/helper.go
- internal/controller/clusterinstance/ownership.go
- internal/controller/clusterinstance/rendered_object.go
- internal/controller/clusterinstance/rendered_object_test.go
- internal/controller/clusterinstance/template_engine.go
- internal/controller/clusterinstance_controller.go
- internal/controller/clusterinstance_controller_test.go
- internal/controller/deletion/deletion.go
- internal/controller/deletion/deletion_test.go
- internal/controller/errors/errors.go
- internal/templates/assisted-installer/template.go
**Enhance SiteConfig Operator Deletion Handling:**   
**PR Description:**  
This pull request introduces significant improvements to the SiteConfig Operator's deletion handling and updates the default assisted-installer template for BareMetalHost.  
- Introduced a `DeletionHandler` to enable graceful deletion of objects owned by a `ClusterInstance` with a configurable timeout.  
- Changed deletion propagation policy to `ForwardPropagationPolicy`.  
- Refactored the `ClusterInstance` finalizer handler to leverage the new `DeletionHandler` and ensure requeuing until all objects are deleted or a timeout occurs.  
- Improved `pruneManifest` functionality for robust object cleanup, integrated with the `DeletionHandler`.  
- Added comprehensive unit tests to validate the new deletion logic. …
> ACM-16142: Enhanced deletion handling for SiteConfig

- config/default/kustomization.yaml
Updates the Kustomize configuration to replace the deprecated patchesStrategicMerge field with the patches field as per Kustomize 5.x recommendations. More details at [CNF-16324](https://issues.redhat.com/browse/CNF-16324).
/cc @sakhoury
> CNF-16324: kustomize: Replace patchesStrategicMerge with patches

- docs/preservation.md
- internal/controller/preservation/helper.go
- internal/controller/preservation/helper_test.go
- internal/controller/preservation/preservation.go
- internal/controller/preservation/preservation_test.go
- internal/controller/preservation/suite_test.go
This PR introduces a data preservation mechanism for backing up and restoring ConfigMaps and Secrets associated with the SiteConfig Operator. It ensures the protection of cluster data during reinstallations by preserving relevant Kubernetes resources in the same namespace as the ClusterInstance CR.
**Key Features:**
- **Preservation Modes**:
- **None**: No preservation.
- **All**: Backs up all ConfigMaps and Secrets labeled with `siteconfig.open-cluster-management.io/preserve`.
- **ClusterIdentity**: Backs up ConfigMaps and Secrets labeled with `siteconfig.open-cluster-management.io/preserve: "cluster-identity"`.
- **Backup Workflow**:
- Preserves Kubernetes resources by sanitizing metadata, removing information (e.g., creation timestamp, owner references), and serializing the resource …
> CNF-15745: Add data preservation functionality to the SiteConfig Operator

- internal/controller/clusterinstance_controller_test.go
- internal/controller/configuration_monitor_test.go
Fixes some issues (mainly cosmetic and small nits) reported by the Go Report Card at https://goreportcard.com/report/github.com/stolostron/siteconfig.
/cc @sakhoury
>  CNF-16397: Fix misspell and gofmt issues detected by Go Report Card

- api/v1alpha1/clusterinstance_types.go
- bundle/manifests/siteconfig.open-cluster-management.io_clusterinstances.yaml
- config/crd/bases/siteconfig.open-cluster-management.io_clusterinstances.yaml
- Each node can individually be specified with an architecture to allow for homogeneous architecture systems
- A default for otherwise unspecified nodes can be provided to ClusterInstanceSpec
- This will require new/modified templates that will be coming later
> CNF-16436: Add CPUArchitecture fields to ClusterInstanceSpec and NodeSpec CRDs

- README.md
Adds the following Badges to the repo's README.md (see [CNF-16467](https://issues.redhat.com/browse/CNF-16467)).
- Go Report Card
- Go Reference for this repo's codebase
- License Apache
/cc @sakhoury 
Follow up PR of #172.
> CNF-16467: Add some badges to README.md

- internal/controller/preservation/helper.go
- internal/controller/preservation/helper_test.go
- internal/controller/preservation/preservation.go
- internal/controller/preservation/preservation_test.go
This commit introduces functions to count the preserved and restored resources.
Resolves: [CNF-16611](https://issues.redhat.com/browse/CNF-16611)
/cc @carbonin
> CNF-16611: Add functionality to determine preservation resource counts

- internal/controller/preservation/helper.go
- internal/controller/reinstall/helper.go
- internal/controller/reinstall/helper_test.go
- internal/controller/reinstall/reinstall.go
- internal/controller/reinstall/reinstall_test.go
This PR extends the `ReinstallHandler` with preservation, restoration, and cleanup functionality. Specifically, 
- Implemented `applyPreservedLabelToClusterInstanceSecrets` to apply a preservation label to ClusterInstance secrets, ensuring they can be backed up and later restored if their ownerReference-linked resources are deleted.
- Added `ensureDataIsPreserved` to back up resources before rendered manifests are deleted.
- Implemented `ensurePreservedDataIsRestored` to restore preserved resources after rendered manifests are deleted.
- Best-effort cleanup of preserved resources in `finalizeReinstallRequest` post-successful restoration.
- Added unit tests for all new and updated functions to validate behaviour.
Resolves: [CNF-16626](https://issues.redhat.com/browse/CNF-16626)
/cc …
> CNF-16626: Extend Reinstall Handler with preservation, restoration, and cleanup

- internal/templates/image-based-installer/template.go
This PR updates the default Image-based Install (IBI) `BareMetalHost` template by setting `online` to `false`. 
Resolves: [ACM-18144](https://issues.redhat.com/browse/ACM-18144)
/cc @carbonin
> ACM-18144: Update default IBI BareMetalHost template

- bundle/manifests/siteconfig.clusterserviceversion.yaml
- config/manager/manager.yaml
The image `gcr.io/kubebuilder/kube-rbac-proxy` is deprecated and will become [unavailable](https://github.com/kubernetes-sigs/kubebuilder/discussions/3907). This commit replaces it with the Red Hat-maintained equivalent to ensure continued support and compatibility.
Resolves: [ACM-18511](https://issues.redhat.com/browse/ACM-18511)
/cc @carbonin
> ACM-18511: Replace deprecated kube-rbac-proxy image

- bundle/manifests/siteconfig.clusterserviceversion.yaml
- config/manager/manager.yaml
This PR adds `--http2-disable=true` to the kube-rbac-proxy args in config/manager/manager.yaml to mitigate CVE-2023-44487 (HTTP/2 Rapid Reset attack). Additionally, `--v=10` is added to enable detailed debug logging.
Resolves: [ACM-18512](https://issues.redhat.com/browse/ACM-18512)
/cc @carbonin @gparvin
> ACM-18512: Disable HTTP/2 in kube-rbac-proxy to mitigate CVE-2023-44487

- bundle/manifests/siteconfig.clusterserviceversion.yaml
- config/manager/manager.yaml
Resolves [ACM-19035](https://issues.redhat.com/browse/ACM-19035)
/cc @carbonin @gparvin
> ACM-19035: Remove --http2-disable argument as it is not supported in the ACM kube-rbac-proxy image

- internal/templates/assisted-installer/template.go
- internal/templates/image-based-installer/template.go
CNF-16437: Enhance templates to allow specifying cluster and node architecture
- Update both assisted-installer and image-based-installer templates to pass the architecture data down from the ClusterInstance
- For assisted-installer, include cpuArchitecture in the InfraEnv template and include architecture in the BareMetalHost template
- For image-based-installer, include architecture in the BareMetalHost template
> CNF-16437: Enhance templates to pass through CPU architecture information

- api/v1alpha1/clusterinstance_validation.go
- api/v1alpha1/clusterinstance_validation_test.go
This PR permits changes to `spec.clusterImageSetNameRef`.
Resolves: [ACM-18970](https://issues.redhat.com/browse/ACM-18970)
/cc @carbonin
> ACM-18970: Allow changes to clusterImageSetNameRef

- api/v1alpha1/clusterinstance_types.go
- bundle/manifests/siteconfig.open-cluster-management.io_clusterinstances.yaml
- config/crd/bases/siteconfig.open-cluster-management.io_clusterinstances.yaml
- internal/templates/assisted-installer/template.go
- internal/templates/image-based-installer/template.go
- The default value from the ClusterInstance should be used if there is no value defined on the Node
- Remove Kubebuilder defaults from the Node field to allow overriding from ClusterInstance
> CNF-16437: Fix cpu architecture templating deficiency

- go.mod
- go.sum
- vendor/golang.org/x/oauth2/LICENSE
- vendor/golang.org/x/oauth2/README.md
- vendor/golang.org/x/oauth2/oauth2.go
- vendor/golang.org/x/oauth2/pkce.go
- vendor/golang.org/x/oauth2/token.go
- vendor/modules.txt
Resolves: [ACM-19576](https://issues.redhat.com/browse/ACM-19576)
/cc @carbonin @aleccohan @gparvin
> ACM-19576: Upversion golang.org/x/oauth2 to address CVE-2025-22868

- .tekton/siteconfig-acm-214-pull-request.yaml
- .tekton/siteconfig-acm-214-push.yaml
- .tekton/siteconfig-main-pull-request.yaml
- .tekton/siteconfig-main-push.yaml
The Konflux Enterprise Contract job is failing due to the following violations:
```sh
✕ [Violation] tasks.required_tasks_found
ImageRef: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/siteconfig-main/siteconfig-main@sha256:79b3991559c9ef8a2afa66feaa6ab0759497f0e3fd8f84f0545c101e42f39875
Reason: One of "sast-shell-check", "sast-shell-check-oci-ta" tasks is missing
Title: All required tasks were included in the pipeline
Description: Ensure that the set of required tasks are included in the PipelineRun attestation. To exclude this rule add one or
more of "tasks.required_tasks_found:sast-shell-check", "tasks.required_tasks_found:sast-shell-check-oci-ta" to the `exclude`
section of the policy configuration.
Solution: Make sure all required tasks are in the build pipeline. The required …
```
> ACM-19748: Add missing konflux tasks

- docs/image_mirroring.md
Documents how to supply mirror images as extra manifests when deploying clusters in disconnected environment with the SiteConfig operator.
Resolves: [ACM-17812](https://issues.redhat.com/browse/ACM-17812)
/cc @sakhoury @trewest
> ACM-17812: Add docs for image mirroring

- docs/reinstallation/README.md
- docs/reinstallation/preservation.md
- docs/reinstallation/status_conditions.md
This PR introduces the following documentation updates:  
- **New documentation:**  
- Cluster reinstallation using the SiteConfig Operator  
- Image-Based Break/Fix (IBBF) for SNO hardware replacement  
- Cluster reinstallation status conditions  
- **File relocation:**  
- Moved `preservation.md` to `docs/reinstallation/` to centralize all reinstallation-related documentation.  
Partially resolves: [TELCODOCS-2014](https://issues.redhat.com/browse/TELCODOCS-2014)
/cc @carbonin @browsell @amolnar-rh @swopebe
> Add cluster reinstallation documentation

- internal/controller/clusterinstance/helper.go
- internal/controller/clusterinstance/helper_test.go
This PR ensures that the number of worker agents is explicitly set to 0 for Single Node OpenShift (SNO) clusters. This change is necessary to comply with immutability restrictions enforced by the Assisted Installer, specifically by the `AgentClusterInstall` resource, which prevents modifying the worker count during or after an attempted SNO expansion.
Resolves: [ACM-20748](https://issues.redhat.com/browse/ACM-20748)
/cc @carbonin
> ACM-20748: Set the number of workers to 0 for SNO

- api/v1alpha1/clusterinstance_validation.go
- api/v1alpha1/clusterinstance_validation_test.go
This PR fixes a bug affecting the admission validating webhook for cluster reinstallation scenarios, where changes to `nodeNetwork.interfaces.macAddress` were incorrectly considered inadmissible.
Resolves: [ACM-20922](https://issues.redhat.com/browse/ACM-20922)
/cc @carbonin
> ACM-20922: Fix admissibility for changes to nodeNetwork.interfaces.macAddress for cluster reinstallations

- sonar-project.properties
This PR adds the `config/` and `bundle/` directories to the sonarqube exclusion list.
/cc @carbonin
> Add config and bundle directories to be excluded by sonarqube

- internal/controller/clusterinstance/helper.go
- internal/controller/clusterinstance/helper_test.go
- internal/controller/clusterinstance/template_engine.go
- internal/controller/clusterinstance/template_engine_test.go
- internal/controller/clusterinstance/test_utils.go
This PR updates the variables available to templates in the `SpecialVars` structure to include a `ReleaseImage` that is populated from the `clusterinstance.spec.clusterImageSetNameRef`.
The purpose of this change is to enable support of cluster installation methods that use the release image as a string, and do not support the `ClusterImageSet` API, namely Hypershift aka Hosted Control Planes.
A lookup of the provided `ClusterImageSet` is performed once per `ClusterInstance` reconcile and is passed by reference through the stack of template engine functions until the `buildClusterData` function uses it to create the `ClusterData` structure for template rendering.
JIRA: [CNF-18294: Reconcile ClusterImage and HostedCluster handling of install …
> CNF-18294: Add a ReleaseImage field to SpecialVars tracking the Cluster Image Set

- .tekton/siteconfig-acm-212-pull-request.yaml
- .tekton/siteconfig-acm-212-push.yaml
- .tekton/siteconfig-acm-215-pull-request.yaml
- .tekton/siteconfig-acm-215-push.yaml
This PR fixes the auto-generated konflux files to reference the appropriate `Dockerfile` for building the siteconfig-operator image.
/cc @dhaiducek  @dislbenn
> NO-ISSUE: Fix konflux pipeline Dockerfile reference

- api/v1alpha1/clusterinstance_validation.go
- api/v1alpha1/clusterinstance_validation_test.go
- api/v1alpha1/clusterinstance_webhook_test.go
The existing ClusterInstance validation logic had several critical limitations when handling complex node array operations:
- Position-dependent node matching: the validation assumed nodes could only be added/removed at the end of arrays, failing when users inserted/removed nodes at an arbitrary position
- Incorrect mixed operation classification: operations like "remove 1 node, add 2 nodes" were incorrectly classified as simple "scale-out" instead of "mixed operations"
This PR introduces a comprehensive refactoring of the ClusterInstance validation system:
- Add support for mixed operations (simultaneous node additions/removals)
- Introduce custom `OperationType` with Mixed, ScaleOut, ScaleIn, Replacement types
- Implement position-independent node matching using stable identifiers
- …
> ACM-21720: Enhance ClusterInstance validation for mixed node operations

- internal/templates/image-based-installer/template.go
Resolves: [ACM-23880](https://issues.redhat.com/browse/ACM-23880)
/cc @carbonin
> ACM-23880: Fix IBI templates to support BareMetalHost references across namespaces

- Dockerfile
- Makefile
- build/Dockerfile.rhtap
- bundle/manifests/siteconfig.clusterserviceversion.yaml
- config/manager/kustomization.yaml
- go.mod
Resolves: [ACM-24105](https://issues.redhat.com/browse/ACM-24105)
/cc @carbonin
> ACM-24105: Bump Go to 1.24 and update Dockerfile builder images

- internal/templates/assisted-installer/template.go
- internal/templates/hosted-cluster/template.go
Add conditional guards around `additionalNTPSources` in assisted-installer and hosted-cluster templates to avoid Server-Side Apply validation errors when the field is empty.
Resolves: [ACM-24685](https://issues.redhat.com/browse/ACM-24685)
/cc @carbonin @achuzhoy
> ACM-24685: Add conditional guards for additionalNTPSources in default templates
