stolostron/siteconfig

- .tekton/siteconfig-unit-test.yaml
- Makefile
This PR contains changes to execute unit-tests as part of the ci-pipeline.
> CNF-13407: Configure pipeline unit-test execution

- README.md
- bundle/manifests/siteconfig.clusterserviceversion.yaml
- cmd/main.go
- cmd/main_test.go
- config/default/kustomization.yaml
- config/manager/manager.yaml
- config/samples/siteconfig_v1alpha1_clusterinstance.yaml
This PR renames the SiteConfig operator namespace from `siteconfig-system` to `siteconfig-operator`.
> CNF-12057: Rename the SiteConfig operator namespace

- .gitattributes
This PR adds the `.gitattributes` file to the siteconfig-operator project.
> CNF-13785: Add gitattributes file

- internal/templates/image-based-install/template.go
This PR updates adds the NMstate secret generating template to the default IBI templates. This is to support the changes introduced in the IBI Operator (https://github.com/openshift/image-based-install-operator/pull/72).
The following network secret was generated by the SiteConfig operator using the newly added IBI template.
```yaml
apiVersion: v1
data:
nmstate: <retracted>
kind: Secret
metadata:
annotations:
siteconfig.open-cluster-management.io/sync-wave: "1"
creationTimestamp: "2024-08-26T16:50:13Z"
labels:
environment.metal3.io: baremetal
name: cnfdg6.ptp.eng.rdu2.dc.redhat.com
namespace: cnfdg6
ownerReferences:
- apiVersion: siteconfig.open-cluster-management.io/v1alpha1
blockOwnerDeletion: true
controller: true
kind: ClusterInstance
name: cnfdg6
uid: …
```
> CNF-14123: Add preprovisioningNetworkDataName BMH support

- Makefile
- bundle/manifests/siteconfig.clusterserviceversion.yaml
- bundle/manifests/siteconfig.open-cluster-management.io_clusterinstances.yaml
- config/crd/bases/siteconfig.open-cluster-management.io_clusterinstances.yaml
- config/manager/kustomization.yaml
- config/rbac/role.yaml
This PR up-versions the controller-gen and kustomize tool versions in the Makefile.
> CNF-14463: Up-version Makefile tools

- internal/templates/assisted-installer/template.go
- internal/templates/image-based-install/template.go
This PR adds conditional guards before attempting to create NodeNetwork-related manifests.
> ACM-14164: Handle DHCP deployments

- internal/controller/clusterinstance_controller.go
- internal/controller/clusterinstance_controller_test.go
This PR refactors the `createOrPatch` function in the `clusterinstance_controller` to better handle updates to previously rendered install manifests. Previously, updates to rendered manifests would result in existing fields being replaced / removed by the default installer template (for example metadata.labels, or metadata.annotations). The refactored approach allows for other fields not-specified in the install template to co-exist. This is necessary as other operators may inject values into these manifests that need to be preserved (i.e. not removed).
Test cases are added to verify the working functionality. 
An e2e manual test was executed by deploying a cluster, Then once provisioning is completed successfully, extra-annoations were applied to the BareMetalHost via the ClusterInstance …
> ACM-14430: Refactor createOrPatch function

- internal/controller/clusterinstance_controller.go
- internal/controller/clusterinstance_controller_test.go
This PR introduces logic to handle updates for objects like `ConfigMap` and `Secret` that lack a spec field. 
Resolves [ACM-16896](https://issues.redhat.com/browse/ACM-16896)
> ACM-16896: Refactor createOrPatch to handle objects without spec fields

- bundle/manifests/siteconfig.clusterserviceversion.yaml
- config/manager/manager.yaml
Resolves: https://issues.redhat.com/browse/ACM-16360
> ACM-16360: Remove resource limits from SiteConfig Operator deployment

- .tekton/siteconfig-acm-212-pull-request.yaml
- .tekton/siteconfig-acm-212-push.yaml
- .tekton/siteconfig-acm-213-pull-request.yaml
- .tekton/siteconfig-acm-213-push.yaml
- .tekton/siteconfig-main-pull-request.yaml
- .tekton/siteconfig-main-push.yaml
- Dockerfile
This PR addresses a number of violations in the recently configured EnterpriseContract IntegrationTestScenario in Konflux.
Resolves: [ACM-17042](https://issues.redhat.com/browse/ACM-17042)
> ACM-17042: Address EnterpriseContract Konflux violations

- internal/controller/preservation/helper.go
- internal/controller/preservation/helper_test.go
- internal/controller/preservation/preservation.go
- internal/controller/preservation/preservation_test.go
This PR consists of the following changes:
- Extended preservation functionality to include backing-up and restoring internal ClusterInstance resources (e.g., pull secrets, BMC credentials).
- Introduced an internal preservation label and value to differentiate internal resources from user-labelled ones.
- Updated existing unit tests and added new tests to verify the correctness of the changes.
Resolves: [CNF-16599](https://issues.redhat.com/browse/CNF-16599)
/cc @carbonin
> CNF-16599: Add support for backup & restore of internal ClusterInstance resources

- internal/controller/preservation/helper.go
- internal/controller/preservation/helper_test.go
This PR contains the following changes:
- Refactored `createResource` to use `controllerutil.CreateOrUpdate`, ensuring existing resources are updated instead of failing on creation.
- Extended unit tests to verify update behaviour when the resource already exists.
Resolves: [CNF-16658](https://issues.redhat.com/browse/CNF-16658)
/cc @carbonin
> CNF-16658: Refactor createResource with update functionality

- docs/troubleshooting.md
> Fix troubleshooting doc references

- docs/cpu_architecture.md
- Add docs/cpu_architecture.md to describe how to define CPU architecture
- Add link to upstream Assisted Installer doc for info on the necessary annotation for ARM
> CNF-16438: Add documentation on how to configure CPU architecture

- docs/cpu_architecture.md
Resolves: https://issues.redhat.com/browse/ACM-19773
/cc @sakhoury
> ACM-19773: Document configuring CPU architecture with ClusterInstance

- .tekton/siteconfig-acm-214-pull-request.yaml
- .tekton/siteconfig-acm-214-push.yaml
Resolves: [ACM-20654](https://issues.redhat.com/browse/ACM-20654)
> ACM-20654: Fix failing konflux pipelines

- .tekton/siteconfig-acm-214-pull-request.yaml
- .tekton/siteconfig-acm-214-push.yaml
Resolves: [ACM-20730](https://issues.redhat.com/browse/ACM-20730)
/cc @dislbenn
> ACM-20730: Remove duplicated konflux tasks

- .tekton/siteconfig-acm-214-push.yaml
- .tekton/siteconfig-main-push.yaml
Resolves: [ACM-20981](https://issues.redhat.com/browse/ACM-20981)
/cc @dislbenn @dhaiducek
> ACM-20981: Enable multi-arch Konflux builds on push pipelines

- cmd/main.go
- cmd/main_test.go
This PR introduces a change to delete existing default installation template ConfigMaps before creating new ones. Since the ConfigMaps are immutable, deleting and recreating them ensures that the latest template versions are applied during operator upgrades.
Resolves: [ACM-21253](https://issues.redhat.com/browse/ACM-21253)
/cc @carbonin @imiller0
> ACM-21253 Ensure Latest ConfigMap Installation Templates on Operator Upgrade

- sonar-project.properties
> Correct SonarQube coverage report file path

- .tekton/siteconfig-acm-215-pull-request.yaml
- .tekton/siteconfig-acm-215-push.yaml
Resolves: [ACM-23261](https://issues.redhat.com/browse/ACM-23261)
/cc @dislbenn @gparvin
> ACM-23261: Fix Enterprise Contract failures for SiteConfig operator in ACM 2.15
